- name: Install Kubernetes
  gather_facts: False
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Add kubeadm repositories on All Nodes
      
      yum_repository:
         name: kube
         description: Kubernetes repo
         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
         enabled: 1
         gpgcheck: 1
         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    
    - name: Installing Docker & kubeadm on All Nodes
      
      package:
        name:
          - docker
          - kubeadm
          - iproute-tc
        state: present

    - name: Staring & enabling Docker All Nodes
    
      service:
        name: "docker"
        state: started
        enabled: yes

    - name: Staring & enabling kubelet on All Nodes
      
      service:
        name: "kubelet"
        state: started
        enabled: yes

    - name: Updating Docker cgroup on All Nodes
      
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
          "exec-opts": ["native.cgroupdriver=systemd"]
          }
    - name: Restart docker on All Nodes
      
      service:
        name: docker
        state: restarted

- name: Master Setup
  gather_facts: False
  hosts: Master_Node
  remote_user: ec2-user
  become: yes
  tasks:   
    - name: Pulling the images of k8s master
      command: kubeadm config images pull
    - name: Initializing k8s cluster
     
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors='all' --v=5



- name: Master Setup
  gather_facts: False
  hosts: Master_Node
  remote_user: ec2-user
  #become: yes
  tasks:
    # - name: Add kubeadm repositories on Master Node
    
      # yum_repository:
      #   name: kube
      #   description: Kubernetes repo
      #   baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      #   enabled: 1
      #   gpgcheck: 1
      #   gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    # - name: Installing Docker & kubeadm on Master Node
      
    #   package:
    #     name:
    #       - docker
    #       - kubeadm
    #       - iproute-tc
    #     state: present

    # - name: Staring & enabling Docker Master Node
    
    #   service:
    #     name: "docker"
    #     state: started
    #     enabled: yes

    # - name: Staring & enabling kubelet on Master Node
      
    #   service:
    #     name: "kubelet"
    #     state: started
    #     enabled: yes
    

    # - name: Pulling the images of k8s master
      
    #   command: kubeadm config images pull

    # - name: Updating Docker cgroup on Master Node
      
    #   copy:
    #     dest: /etc/docker/daemon.json
    #     content: |
    #       {
    #       "exec-opts": ["native.cgroupdriver=systemd"]
    #       }
    # - name: Restart docker on Master Node
      
    #   service:
    #     name: docker
    #     state: restarted

    # - name: Initializing k8s cluster
      
    #   command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors='all' --v=5

    - name: Setting up kubectl on Master Node
      
      shell:
        cmd: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config


    - name: Deploying Flannel on Master Node
     
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Creating token for Worker

      command: kubeadm token create  --print-join-command
      register: token



- name: Workers Setup
  gather_facts: False
  hosts: Worker_Node
  remote_user: ec2-user
  become: yes
  tasks:

    # - name: Add kubeadm repositories on Slave Node
    #   yum_repository:
    #     name: kube
    #     description: Kubernetes repo
    #     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    #     enabled: 1
    #     gpgcheck: 1
    #     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    # - name: Installing Docker & kubeadm on Slave Node
    #   package:
    #     name:
    #       - docker
    #       - kubeadm
    #       - iproute-tc
    #     state: present

    # - name: Staring & enabling Docker on Slave Node
    #   service:
    #     name: "docker"
    #     state: started
    #     enabled: yes
     
    
    # - name: Staring & enabling kubelet on Slave Node
    #   service:
    #     name: "kubelet"
    #     state: started
    #     enabled: yes
     

    # - name: Updating Docker cgroup on Slave Node
    #   copy:
    #     dest: /etc/docker/daemon.json
    #     content: |
    #       {
    #       "exec-opts": ["native.cgroupdriver=systemd"]
    #       }
    # - name: Restart Docker on Slave Node
    #   service:
    #     name: docker
    #     state: restarted

    - name: Updating IP tables on Worker Node
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables =1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Reloading sysctl on Worker Node
      command: sysctl --system

    - name: Joining the master node
      command: "{{ hostvars[groups['Master_Node'][0]]['token']['stdout'] }}"

